# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneshot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneshot.proto',
  package='shell_wrapper',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\roneshot.proto\x12\rshell_wrapper\"\xb9\x03\n\nRunRequest\x12\x1e\n\x16\x63ommand_line_parameter\x18\x01 \x03(\t\x12\r\n\x05stdin\x18\x02 \x01(\x0c\x12>\n\x0binput_files\x18\x03 \x03(\x0b\x32).shell_wrapper.RunRequest.InputFilesEntry\x12@\n\x0coutput_files\x18\x04 \x03(\x0b\x32*.shell_wrapper.RunRequest.OutputFilesEntry\x12\x15\n\robtain_stdout\x18\x05 \x01(\x08\x12\x15\n\robtain_stderr\x18\x06 \x01(\x08\x12\x1d\n\x15\x63ombine_stdout_stderr\x18\x07 \x01(\x08\x12\x0f\n\x07timeout\x18\x08 \x01(\x05\x1aK\n\x0fInputFilesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.shell_wrapper.InputFile:\x02\x38\x01\x1aO\n\x10OutputFilesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.shell_wrapper.FileLocation:\x02\x38\x01\".\n\x0c\x46ileLocation\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x03(\t\"i\n\x0bRunResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rrequest_error\x18\x02 \x01(\t\x12\x32\n\rtool_response\x18\x03 \x01(\x0b\x32\x1b.shell_wrapper.ToolResponse\"r\n\x0cToolResponse\x12\x10\n\x08\x65xitcode\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\x0c\x12\x0e\n\x06stderr\x18\x03 \x01(\x0c\x12\x30\n\x0coutput_files\x18\x04 \x03(\x0b\x32\x1a.shell_wrapper.FileContent\"Z\n\x0b\x46ileContent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12-\n\x08location\x18\x03 \x01(\x0b\x32\x1b.shell_wrapper.FileLocation\"K\n\tInputFile\x12-\n\x08location\x18\x01 \x01(\x0b\x32\x1b.shell_wrapper.FileLocation\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x32N\n\x0eShellComponent\x12<\n\x03Run\x12\x19.shell_wrapper.RunRequest\x1a\x1a.shell_wrapper.RunResponseb\x06proto3')
)




_RUNREQUEST_INPUTFILESENTRY = _descriptor.Descriptor(
  name='InputFilesEntry',
  full_name='shell_wrapper.RunRequest.InputFilesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='shell_wrapper.RunRequest.InputFilesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='shell_wrapper.RunRequest.InputFilesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=393,
)

_RUNREQUEST_OUTPUTFILESENTRY = _descriptor.Descriptor(
  name='OutputFilesEntry',
  full_name='shell_wrapper.RunRequest.OutputFilesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='shell_wrapper.RunRequest.OutputFilesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='shell_wrapper.RunRequest.OutputFilesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=474,
)

_RUNREQUEST = _descriptor.Descriptor(
  name='RunRequest',
  full_name='shell_wrapper.RunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_line_parameter', full_name='shell_wrapper.RunRequest.command_line_parameter', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdin', full_name='shell_wrapper.RunRequest.stdin', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_files', full_name='shell_wrapper.RunRequest.input_files', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_files', full_name='shell_wrapper.RunRequest.output_files', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obtain_stdout', full_name='shell_wrapper.RunRequest.obtain_stdout', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obtain_stderr', full_name='shell_wrapper.RunRequest.obtain_stderr', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='combine_stdout_stderr', full_name='shell_wrapper.RunRequest.combine_stdout_stderr', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='shell_wrapper.RunRequest.timeout', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RUNREQUEST_INPUTFILESENTRY, _RUNREQUEST_OUTPUTFILESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=474,
)


_FILELOCATION = _descriptor.Descriptor(
  name='FileLocation',
  full_name='shell_wrapper.FileLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='shell_wrapper.FileLocation.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='shell_wrapper.FileLocation.path', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=522,
)


_RUNRESPONSE = _descriptor.Descriptor(
  name='RunResponse',
  full_name='shell_wrapper.RunResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='shell_wrapper.RunResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_error', full_name='shell_wrapper.RunResponse.request_error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tool_response', full_name='shell_wrapper.RunResponse.tool_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=629,
)


_TOOLRESPONSE = _descriptor.Descriptor(
  name='ToolResponse',
  full_name='shell_wrapper.ToolResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exitcode', full_name='shell_wrapper.ToolResponse.exitcode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdout', full_name='shell_wrapper.ToolResponse.stdout', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='shell_wrapper.ToolResponse.stderr', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_files', full_name='shell_wrapper.ToolResponse.output_files', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=745,
)


_FILECONTENT = _descriptor.Descriptor(
  name='FileContent',
  full_name='shell_wrapper.FileContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='shell_wrapper.FileContent.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='shell_wrapper.FileContent.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='shell_wrapper.FileContent.location', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=747,
  serialized_end=837,
)


_INPUTFILE = _descriptor.Descriptor(
  name='InputFile',
  full_name='shell_wrapper.InputFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='shell_wrapper.InputFile.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='shell_wrapper.InputFile.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=839,
  serialized_end=914,
)

_RUNREQUEST_INPUTFILESENTRY.fields_by_name['value'].message_type = _INPUTFILE
_RUNREQUEST_INPUTFILESENTRY.containing_type = _RUNREQUEST
_RUNREQUEST_OUTPUTFILESENTRY.fields_by_name['value'].message_type = _FILELOCATION
_RUNREQUEST_OUTPUTFILESENTRY.containing_type = _RUNREQUEST
_RUNREQUEST.fields_by_name['input_files'].message_type = _RUNREQUEST_INPUTFILESENTRY
_RUNREQUEST.fields_by_name['output_files'].message_type = _RUNREQUEST_OUTPUTFILESENTRY
_RUNRESPONSE.fields_by_name['tool_response'].message_type = _TOOLRESPONSE
_TOOLRESPONSE.fields_by_name['output_files'].message_type = _FILECONTENT
_FILECONTENT.fields_by_name['location'].message_type = _FILELOCATION
_INPUTFILE.fields_by_name['location'].message_type = _FILELOCATION
DESCRIPTOR.message_types_by_name['RunRequest'] = _RUNREQUEST
DESCRIPTOR.message_types_by_name['FileLocation'] = _FILELOCATION
DESCRIPTOR.message_types_by_name['RunResponse'] = _RUNRESPONSE
DESCRIPTOR.message_types_by_name['ToolResponse'] = _TOOLRESPONSE
DESCRIPTOR.message_types_by_name['FileContent'] = _FILECONTENT
DESCRIPTOR.message_types_by_name['InputFile'] = _INPUTFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunRequest = _reflection.GeneratedProtocolMessageType('RunRequest', (_message.Message,), dict(

  InputFilesEntry = _reflection.GeneratedProtocolMessageType('InputFilesEntry', (_message.Message,), dict(
    DESCRIPTOR = _RUNREQUEST_INPUTFILESENTRY,
    __module__ = 'oneshot_pb2'
    # @@protoc_insertion_point(class_scope:shell_wrapper.RunRequest.InputFilesEntry)
    ))
  ,

  OutputFilesEntry = _reflection.GeneratedProtocolMessageType('OutputFilesEntry', (_message.Message,), dict(
    DESCRIPTOR = _RUNREQUEST_OUTPUTFILESENTRY,
    __module__ = 'oneshot_pb2'
    # @@protoc_insertion_point(class_scope:shell_wrapper.RunRequest.OutputFilesEntry)
    ))
  ,
  DESCRIPTOR = _RUNREQUEST,
  __module__ = 'oneshot_pb2'
  # @@protoc_insertion_point(class_scope:shell_wrapper.RunRequest)
  ))
_sym_db.RegisterMessage(RunRequest)
_sym_db.RegisterMessage(RunRequest.InputFilesEntry)
_sym_db.RegisterMessage(RunRequest.OutputFilesEntry)

FileLocation = _reflection.GeneratedProtocolMessageType('FileLocation', (_message.Message,), dict(
  DESCRIPTOR = _FILELOCATION,
  __module__ = 'oneshot_pb2'
  # @@protoc_insertion_point(class_scope:shell_wrapper.FileLocation)
  ))
_sym_db.RegisterMessage(FileLocation)

RunResponse = _reflection.GeneratedProtocolMessageType('RunResponse', (_message.Message,), dict(
  DESCRIPTOR = _RUNRESPONSE,
  __module__ = 'oneshot_pb2'
  # @@protoc_insertion_point(class_scope:shell_wrapper.RunResponse)
  ))
_sym_db.RegisterMessage(RunResponse)

ToolResponse = _reflection.GeneratedProtocolMessageType('ToolResponse', (_message.Message,), dict(
  DESCRIPTOR = _TOOLRESPONSE,
  __module__ = 'oneshot_pb2'
  # @@protoc_insertion_point(class_scope:shell_wrapper.ToolResponse)
  ))
_sym_db.RegisterMessage(ToolResponse)

FileContent = _reflection.GeneratedProtocolMessageType('FileContent', (_message.Message,), dict(
  DESCRIPTOR = _FILECONTENT,
  __module__ = 'oneshot_pb2'
  # @@protoc_insertion_point(class_scope:shell_wrapper.FileContent)
  ))
_sym_db.RegisterMessage(FileContent)

InputFile = _reflection.GeneratedProtocolMessageType('InputFile', (_message.Message,), dict(
  DESCRIPTOR = _INPUTFILE,
  __module__ = 'oneshot_pb2'
  # @@protoc_insertion_point(class_scope:shell_wrapper.InputFile)
  ))
_sym_db.RegisterMessage(InputFile)


_RUNREQUEST_INPUTFILESENTRY._options = None
_RUNREQUEST_OUTPUTFILESENTRY._options = None

_SHELLCOMPONENT = _descriptor.ServiceDescriptor(
  name='ShellComponent',
  full_name='shell_wrapper.ShellComponent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=916,
  serialized_end=994,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='shell_wrapper.ShellComponent.Run',
    index=0,
    containing_service=None,
    input_type=_RUNREQUEST,
    output_type=_RUNRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHELLCOMPONENT)

DESCRIPTOR.services_by_name['ShellComponent'] = _SHELLCOMPONENT

# @@protoc_insertion_point(module_scope)
