# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import oneshot_pb2 as oneshot__pb2


class ShellComponentStub(object):
  """main entry point
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Run = channel.unary_unary(
        '/shell_wrapper.ShellComponent/Run',
        request_serializer=oneshot__pb2.RunRequest.SerializeToString,
        response_deserializer=oneshot__pb2.RunResponse.FromString,
        )


class ShellComponentServicer(object):
  """main entry point
  """

  def Run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ShellComponentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Run': grpc.unary_unary_rpc_method_handler(
          servicer.Run,
          request_deserializer=oneshot__pb2.RunRequest.FromString,
          response_serializer=oneshot__pb2.RunResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'shell_wrapper.ShellComponent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
